blank_issues_enabled: true
contact_links:
  - name: Questions & discussions
    url: https://github.com/connectors-testing-pplx/vantage-tfsa-calculator/discussions
    about: Ask questions and start discussions here.
